security:
  password:
    min-length: 5

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: ${ACTIVE_PROFILE}
  jpa:
    hibernate:
      ddl-auto: create
springdoc:
  api-docs:
    path: /api-docs
